# Generated by Django 3.2.9 on 2021-12-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cookingTime', models.TimeField(auto_now_add=True, null=True)),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ownership', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPUTER', 'Computer')], max_length=15)),
                ('owner_name', models.CharField(max_length=30)),
                ('rating', models.CharField(choices=[('1STAR', '1star'), ('2STAR', '2star'), ('3STAR', '3star'), ('4STAR', '4star'), ('5STAR', '5star')], max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Serves', to='restaurant.dishes')),
            ],
        ),
    ]
