# Generated by Django 3.2.9 on 2021-12-05 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_auto_20211204_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Dish', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Restaurant', to='auth.user'),
            preserve_default=False,
        ),
    ]
