# Generated by Django 3.2.9 on 2021-12-05 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_auto_20211205_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishez', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
